version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"             
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Madrid"                 
    open-pull-requests-limit: 3
    target-branch: "main"   
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-type: "direct"
    assignees:
      - "sanbricio"
    groups:
      all-dependencies:
        patterns:
          - "*"