package filesetup

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"github.com/sanbricio/goconcurrencylint/pkg/analyzer/internal/common/category"
	"github.com/sanbricio/goconcurrencylint/pkg/analyzer/internal/common/commentfilter"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/analysis"
)

// makeTokenFile registers a 1-byte file in fset and returns its *token.File.
// Used to obtain a *token.File handle without parsing a real source file.
func makeTokenFile(fset *token.FileSet, name string) *token.File {
	return fset.AddFile(name, -1, 1)
}

func TestResultIsGenerated(t *testing.T) {
	fset := token.NewFileSet()
	known := makeTokenFile(fset, "known.go")
	other := makeTokenFile(fset, "other.go")

	res := &Result{
		Generated: map[*token.File]struct{}{known: {}},
	}

	assert.False(t, (*Result)(nil).IsGenerated(known), "nil receiver must be safe and return false")
	assert.False(t, res.IsGenerated(nil), "nil tokFile must return false")
	assert.False(t, res.IsGenerated(other), "tokFile not in the map must return false")
	assert.True(t, res.IsGenerated(known), "tokFile present in the map must return true")
}

func TestResultFilterFor(t *testing.T) {
	fset := token.NewFileSet()
	tokFile := makeTokenFile(fset, "real.go")
	missing := makeTokenFile(fset, "missing.go")

	filter := &commentfilter.CommentFilter{}
	res := &Result{
		Filters: map[string]*commentfilter.CommentFilter{"real.go": filter},
	}

	assert.Nil(t, (*Result)(nil).FilterFor(tokFile), "nil receiver must return nil")
	assert.Nil(t, res.FilterFor(nil), "nil tokFile must return nil")
	assert.Nil(t, res.FilterFor(missing), "unknown filename must return nil")
	assert.Same(t, filter, res.FilterFor(tokFile), "must return the stored filter pointer")
}

func TestResultIgnoreFuncNilCases(t *testing.T) {
	assert.Nil(t, (*Result)(nil).IgnoreFunc(), "nil receiver must return a nil IgnoreFunc")

	empty := &Result{Filters: map[string]*commentfilter.CommentFilter{}}
	assert.Nil(t, empty.IgnoreFunc(), "empty Filters must return a nil IgnoreFunc")
}

// TestResultIgnoreFuncConsultsFilters verifies that the returned IgnoreFunc
// routes filename→filter and that the lookup falls back to false when the
// filename is not in the map.
func TestResultIgnoreFuncConsultsFilters(t *testing.T) {
	src := `package p

func F() {
	// goconcurrencylint:ignore lock-without-unlock
	_ = 0
}
`
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "real.go", src, parser.ParseComments)
	require.NoError(t, err)

	cf := commentfilter.NewCommentFilter(fset, file)
	require.Equal(t, "real.go", cf.FileName(), "CommentFilter must expose the filename it was built from")

	directiveLine := -1
	for _, group := range file.Comments {
		for _, c := range group.List {
			if c.Text == "// goconcurrencylint:ignore lock-without-unlock" {
				directiveLine = fset.Position(c.Pos()).Line
			}
		}
	}
	require.NotEqual(t, -1, directiveLine, "test setup: ignore directive comment not found")

	res := &Result{Filters: map[string]*commentfilter.CommentFilter{"real.go": cf}}
	ignore := res.IgnoreFunc()
	require.NotNil(t, ignore, "non-empty Filters must yield a non-nil IgnoreFunc")

	assert.True(t, ignore("real.go", directiveLine, category.LockWithoutUnlock),
		"directive line must silence the matching category")
	assert.False(t, ignore("real.go", directiveLine, category.WaitWithoutAdd),
		"directive line must not silence a non-listed category")
	assert.False(t, ignore("real.go", directiveLine+10, category.LockWithoutUnlock),
		"unrelated line must not be silenced")
	assert.False(t, ignore("unknown.go", directiveLine, category.LockWithoutUnlock),
		"unknown filename must fall back to false")
}

// TestRunPartitionsFilesByGeneratedFlag runs the Analyzer end-to-end on a
// synthetic Pass containing one generated file and one hand-written file,
// and verifies the resulting partition.
func TestRunPartitionsFilesByGeneratedFlag(t *testing.T) {
	const generatedSrc = `// Code generated by test. DO NOT EDIT.

package p

func G() {}
`
	const normalSrc = `package p

func N() {}
`
	fset := token.NewFileSet()
	genFile, err := parser.ParseFile(fset, "generated.go", generatedSrc, parser.ParseComments)
	require.NoError(t, err)
	normalFile, err := parser.ParseFile(fset, "normal.go", normalSrc, parser.ParseComments)
	require.NoError(t, err)

	pass := &analysis.Pass{
		Fset:  fset,
		Files: []*ast.File{genFile, normalFile},
	}

	raw, err := Analyzer.Run(pass)
	require.NoError(t, err)
	res, ok := raw.(*Result)
	require.True(t, ok, "Analyzer.Run must return *Result, got %T", raw)

	genTokFile := fset.File(genFile.Pos())
	normalTokFile := fset.File(normalFile.Pos())
	require.NotNil(t, genTokFile)
	require.NotNil(t, normalTokFile)

	assert.True(t, res.IsGenerated(genTokFile), "generated file must be flagged")
	assert.False(t, res.IsGenerated(normalTokFile), "hand-written file must not be flagged")

	assert.NotContains(t, res.Filters, "generated.go",
		"generated files must not get a CommentFilter (their diagnostics are skipped anyway)")
	assert.NotNil(t, res.FilterFor(normalTokFile),
		"hand-written file must have an associated CommentFilter")
}
